"""empty message

Revision ID: e63f6bc46b97
Revises: 05ad490da885
Create Date: 2023-10-10 00:28:01.534389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63f6bc46b97'
down_revision: Union[str, None] = '05ad490da885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('nickname', sa.Text(), nullable=False),
    sa.Column('mbti', sa.Text(), nullable=True),
    sa.Column('jwt_token', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
